Htaq translate
kottans/frontend pull request #363
Opened 2022-06-03 21:44 UTC by artem-trubin

Translated HTAQ.md file. There are some TODOs, for example where list of chats must be (since we don't have newly created chats yet) and Table Of Content must be regenerated, I'm not sure how to do it.

2022-06-04 12:21 UTC, A-Ostrovnyy requested changes
Good work!

2022-06-04 12:21 UTC, A-Ostrovnyy commented on HTAQ.md
> +**Іноді може здаватись що ми відштовхуюче грубі з новаками, або приділяємо їм мало уваги. Але насправді це зовсім не так. Будь ласка, спробуйте краще задати питання :smile_cat:**
новачками

2022-06-04 12:21 UTC, A-Ostrovnyy commented on HTAQ.md
> +_Щоб надати зворотній зв'язок за вашим питанням, будь ласка, використовуйте структуру запитування, що наведена нижче. Авжеж, конкретні слова не повинні бути такими самими, все залежить від вашої ситу
`структуру питання` or `структуру запитів`

2022-06-04 12:21 UTC, A-Ostrovnyy commented on HTAQ.md
> +Не поспішайте. Не очікуйте, що вдасться вирішити складну проблему парою секунд Гуглінгу. Розслабтесь, візміть чашку чаю та добряче подумайте над проблему перш ніж турбувати експертів. Повірте, вони з
`подумайте над проблемою` or 'обдумайте проблему'

2022-06-04 18:31 UTC, suchov approved these changes

2022-06-05 09:55 UTC, suchov commented
asked @A-Ostrovnyy to review one more time

2022-06-05 09:57 UTC, A-Ostrovnyy approved these changes

2022-06-05 09:57 UTC, merged

2022-06-05 09:58 UTC, A-Ostrovnyy commented
Awesome!