Translated stage0-finishers.md
kottans/frontend pull request #366
Opened 2022-06-14 20:14 UTC by artem-trubin

Перекладено #365

2022-06-15 15:20 UTC, suchov approved these changes

2022-06-15 15:27 UTC, boxdxnx requested changes

2022-06-15 15:27 UTC, boxdxnx commented on students/stage0-finishers.md
> +_Якщо ви редактуєте файл через інтерфейс GitHub, додайте 2 порожніх рядки у кінці._
редагуєте

2022-06-15 16:55 UTC, Roophee commented on students/stage0-finishers.md
> +[15 вправ (з 0 по 14)](https://github.com/kottans/frontend/blob/master/contents.md),
Завдань? Тематичних блоків?

2022-06-15 16:59 UTC, Roophee commented on students/stage0-finishers.md
> +змінити свій запис пізніше, якщо захочете доробити необов'язкові вправи.
якщо буде бажання?

2022-06-15 17:10 UTC, Roophee commented on students/stage0-finishers.md
> +- **Дата** це дата, в яку ви виконали обов'язкові вправи (дата останнього коміту
на яку ви виконали

2022-06-19 19:01 UTC, artem-trubin commented on students/stage0-finishers.md
> +[15 вправ (з 0 по 14)](https://github.com/kottans/frontend/blob/master/contents.md),
Особисто мені тут більше подобається вправа, тому що у нас невеличкі завдання, саме як було у школі або універі, теж вправами звались.

2022-06-19 19:01 UTC, artem-trubin commented on students/stage0-finishers.md
> +[15 вправ (з 0 по 14)](https://github.com/kottans/frontend/blob/master/contents.md),
Можна авжеж і завдання, але я б ще почув третю думку, бо раніше як вправи перекладав.

2022-06-20 12:33 UTC, Roophee approved these changes

2022-06-20 20:38 UTC, boxdxnx approved these changes

2022-06-22 16:29 UTC, merged