Typos fix and rewordings
kottans/frontend pull request #387
Opened 2022-07-17 13:57 UTC by artem-trubin

- Виправлено орфографічні помилки
- Перефразовані деякі вирази
- Видалено деякі російськомовні матеріали, або замінено на англомовні оригінали

2022-07-17 17:55 UTC, suchov approved these changes

2022-07-18 06:47 UTC, A-Ostrovnyy requested changes
Good work!

2022-07-18 06:47 UTC, A-Ostrovnyy commented on CONTRIBUTING.md
> -якщо хтось просто шукає коміти в історії з компактним відображенням.
@artem-trubin можливо буде зрозуміліше: `у компактному вигляді`

2022-07-18 06:47 UTC, A-Ostrovnyy commented on README.md
>  <!-- TODO: Dates -->
Ми вже назначили дату початку курсу [https://twitter.com/kottans_org/status/1548753163855052801](https://twitter.com/kottans_org/status/1548753163855052801)

2022-07-18 06:47 UTC, A-Ostrovnyy commented on tasks/app-design-offline.md
> +   і помістіть його в теку `task_offline_web_app`
Якщо обираємо такий варіант то треба пройтись по всьму проекту і замінити `папку -> теку`

2022-07-18 06:47 UTC, A-Ostrovnyy commented on tasks/friends-app.md
> +- зрозуміти плюси та мінуси незмінності даних на прикладі копій масивів
Як на мене то краще вже написати `імутабельності (незмінності)` хоч це і англіцизм та в роботі вони частіше будуть чути та використовувати саме його.

2022-07-18 06:47 UTC, A-Ostrovnyy commented on tasks/git-intro.md
> +    Подбайте про те, щоб дати своєму PR значуще ім’я та опис.
`значуще (осмислене)` як ти думаєш?

2022-07-18 06:47 UTC, A-Ostrovnyy commented on tasks/js-oop.md
> -- [Вы не знаете JS: Область видимости и замыкания](https://github.com/azat-io/you-dont-know-js-ru/tree/master/scope%20%26%20closures)
Можливо є сенс замінити посилання на оригінал автора, як це було з першою книгою:

- [You Don't Know JS: Scope & Closures](https://github.com/getify/You-Dont-Know-JS/tree/1st-ed/scope%20%26%20closures)
- [You Don't Know JS: this & Object Prototypes](https://github.com/getify/You-Dont-Know-JS/tree/1st-ed/this%20%26%20object%20prototypes)

2022-07-18 06:53 UTC, artem-trubin commented on tasks/js-oop.md
> -- [Вы не знаете JS: Область видимости и замыкания](https://github.com/azat-io/you-dont-know-js-ru/tree/master/scope%20%26%20closures)
А там же прямо трьома рядками вище як раз оригінали.

2022-07-19 16:58 UTC, A-Ostrovnyy approved these changes

2022-07-19 16:58 UTC, merged