Layouts techniques summary
Kottans/frontend pull request #454
Opened 2022-11-18 13:23 UTC by viktor-yakubiv

Work in progress so far 🚧 Pushing to GitHub to check how it looks in their rendering engine.

2022-11-21 13:32 UTC, A-Ostrovnyy requested changes
LGTM

2022-11-21 13:32 UTC, A-Ostrovnyy commented on notes/css-layouts.md
> +На варстку отримується макет із уже чітко визначеними областями контенту,
```suggestion
На вeрстку отримується макет із уже чітко визначеними областями контенту,
```

2022-11-21 13:32 UTC, A-Ostrovnyy commented on notes/css-layouts.md
> +Можливість блоків «перескакувати», коли їм не вистачає місця,
```suggestion
Можливість блоків «перестрибувати», коли їм не вистачає місця,
```

2022-11-21 13:32 UTC, A-Ostrovnyy commented on notes/css-layouts.md
> +Коли почав зароджуватися веб-дизайн, різноманіття екранів не була,
```suggestion
Коли почав зароджуватися веб-дизайн, різноманіття екранів не було,
```

2022-11-21 13:32 UTC, A-Ostrovnyy commented on notes/css-layouts.md
> +щоб він відображав замисл.
```suggestion
щоб він відображав ідею.
```
?

2022-11-21 15:20 UTC, viktor-yakubiv commented on notes/css-layouts.md
> +Можливість блоків «перескакувати», коли їм не вистачає місця,
Та це [нормальне українське слово](http://sum.in.ua/s/pereskakuvaty). Не все, що звучить, як російська, — то російська.

Але я поправлю, бо звучить краще.

2022-11-21 15:25 UTC, viktor-yakubiv commented on notes/css-layouts.md
> +щоб він відображав замисл.
«[Ідея](http://sum.in.ua/s/ideja)» відображає реальність, «[замисел](http://sum.in.ua/s/zamysel)» чи «задум» відобажається **на** реальність, тобто є бажання щось принести в реальність.

Тут мається на увазі саме втілення, тому я би залишив те, що є, або вибрав «задум».

2022-11-22 11:28 UTC, suchov approved these changes

2022-11-22 19:31 UTC, A-Ostrovnyy approved these changes

2022-11-22 19:31 UTC, merged